### ISSUE TITLE
	path type of the values file is in a wrong place.

### ISSUE THREAD

**Issue by AlirezaPourchali** [aahemm/helm-microservice#1]
https://github.com/aahemm/helm-microservice/blob/f5186c088c67f00fa6d98a6e53ab0291a848b8e2/values.yaml#L163

in the template it is used as '{{ .Values.ingress.hosts.pathType }}'
but in the values file its stated as '{{ .Values.ingress.pathType }}

this can be fixed either by writing `pathType` inside `- host` indent in values file or by changing the ingress template file

**Comment by aahemm** [comment]
Thanks for reporting this issue. It is fixed in ecc4df6
